[package]
name = "pyaga8"
version = "0.1.14"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyaga8"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.1"
aga8 = "0.5"
